###
//login
POST http://localhost:4000/api/v1/user/auth/login
Accept: application/json
Content-Type: application/json

  {
    "usernameOrEmail":"abdulgopur2306@gmail.com",
    "password":"password"
  }

###
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 584
ETag: W/"248-pWCblqN3YSq6sKIHp5Up7qXab6E"
Date: Wed, 11 Aug 2021 14:25:23 GMT
Connection: close

{
  "status": 200,
  "msg": "Success.!",
  "err": null,
  "data": {
    "user": {
      "photo_profile": null,
      "roles": "dev",
      "_id": "610e7b12f5884f4198e7a3d5",
      "numberPhone": "08980354641",
      "username": "apuystereo717",
      "fullName": "apuy stereo",
      "email": "abdulgopur2306@gmail.com",
      "createdAt": "2021-08-07T12:22:42.338Z",
      "updatedAt": "2021-08-07T12:22:42.338Z"
    },
    "accessToken": "eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGU3YjEyZjU4ODRmNDE5OGU3YTNkNSIsInVzZXJuYW1lIjoiYXB1eXN0ZXJlbzcxNyIsInJvbGUiOiJkZXYiLCJpYXQiOjE2Mjg2OTE5MjMsImV4cCI6MTYyODY5NTUyM30.rd6nKTptZRoB2UKb9dt31TxXJAkMrO_Y-yLqzZALg7cL1TMsX0lb_sp42cGxCGeC"
  }
}



###
//register
POST http://localhost:4000/api/v1/user/auth/register
Accept: application/json
Content-Type: application/json

  {
    "username":"kevin717",
    "fullName":"fairuz kevin dh",
    "email":"kevin@gmail.com",
    "country":"indonesia",
    "countryCode":"id",
    "password":"password",
    "cPassword":"password" 
  }



###
//activation
GET http://localhost:4000/api/v1/user/activation/apuystereo/0b1628
Accept: application/json
Content-Type: application/json

###
//check already exist value user example username or email tergantung q = username or email
GET http://localhost:4000/api/v1/user/auth/register-validator
?q=username
&val=apuystereo717
Accept: application/json

###
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 79
ETag: W/"4f-6HpGwLegEoAi/RZ7SqEvmLpZfoA"
Date: Wed, 11 Aug 2021 14:24:34 GMT
Connection: close

{
  "status": 200,
  "msg": "Success.!",
  "err": null,
  "data": {
    "username": "apuystereo717"
  }
}


###
//get link forget password
PUT http://localhost:4000/api/v1/user/forget-password
Accept: application/json
Content-Type: application/json

  {
    "email":"abdulgopurs2306@gmail.com"
  }

###
//verify change-password
PUT http://localhost:4000/api/v1/user/verify-forget-password/apuystereo717/b5b2f4152d33929a.1628963316124.5b2f4152d33929a7
Accept: application/json
Content-Type: application/json

  {
    "nPassword":"new-password",
    "cPassword":"new-password"
  }

###
//change-password
PUT http://localhost:4000/api/v1/user/change-password
Accept: application/json
Content-Type: application/json

  {
    "lPassword":"new-passwords",
    "nPassword":"password717",
    "cPassword":"password717"
  }




###
//change-password
//params username and ctx = reset-password || activation
###
GET http://localhost:4000/api/v1/user/auth/resend-email/apuystereo/activation
Accept: application/json

###
//get list country
###
GET http://localhost:4000/api/v1/list-country
Accept: application/json

###
//search user
###
GET http://localhost:4000/api/v1/user/search/?keyword=moza
Accept: application/json

###
//create room
###
POST http://localhost:4000/api/v1/chat/new-chat
Accept: application/json
Content-Type: application/json

  {
    "_sender": {
      "_id": "61d1ca46fa7a161cc09865d8",
      "sent": false
    },
    "_receiver": {
      "_id": "61d322dd9297533fe8f90204",
      "read": false
    }
  } 


###
//send message
###
POST http://localhost:4000/api/v1/chat/send
Accept: application/json
Content-Type: application/json

  {
    "_listChatId":"61d3233d9297533fe8f90205",
    "_sender": {
      "_id": "61d1ca6cfa7a161cc09865d9",
      "sent": true
    },
    "_receiver": {
      "_id": "61d1ca46fa7a161cc09865d8",
      "read": false
    },
    "body": {
      "fromLang": "id",
      "fromChat": "saya lagi ngoding sama temen",
      "targetLang":"en",
      "targetChat": "I'm coding with my friend"
    }
  } 

###
//get chat
###
GET http://localhost:4000/api/v1/chat/current-chat?_page=1&_limit=10&_listchatId=61d3233d9297533fe8f90205
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDFjYTQ2ZmE3YTE2MWNjMDk4NjVkOCIsInVzZXJuYW1lIjoiYXB1eXN0ZXJlbyIsImlhdCI6MTY0MTIzNDMyNSwiZXhwIjoxNjQxMzIwNzI1fQ.clzG04fGITQwSVImP3UEKIC3Kdc89DjHKZ7-UvC0NVnhAW_yAfiD9U2upjQKx01q

###
//get listChat
###
GET http://localhost:4000/api/v1/chat/list-chat
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDFjYTQ2ZmE3YTE2MWNjMDk4NjVkOCIsInVzZXJuYW1lIjoiYXB1eXN0ZXJlbyIsImlhdCI6MTY0MTIzNDMyNSwiZXhwIjoxNjQxMzIwNzI1fQ.clzG04fGITQwSVImP3UEKIC3Kdc89DjHKZ7-UvC0NVnhAW_yAfiD9U2upjQKx01q