###
//getStreaming
GET http://localhost:3001/api/v1/streaming


###
//getStreaming
POST http://localhost:3001/api/v1/streaming/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzFmNGEzZWRjOWM4MWFhMDVhZjRhMiIsInVzZXJuYW1lIjoiYXB1eXN0ZXJlbzcxNyIsInJvbGUiOiJkZXYiLCJpYXQiOjE2MzQyOTc0MjcsImV4cCI6MTYzNDMwMTAyN30.d527Sbsq6DAh_Z1ZfHqX_hBmCPG65d6icKGL89FAZoXfzC5a9xEoNkjYIS87BKs-

  {
    "_userId":"6128ca8ab315610a2411e787",
    "title": "PENGAJIAN AHAD PAGI || 03-09-2021",
    "tags": "ahad-pagi, alhikam, kedunglo",
    "isPrivate": false,
    "desc": "-"
  }